### ISSUE TITLE
Doesn't connect entities properly

### ISSUE THREAD

**Issue by chang-zhao** [selfthinker/dokuwiki_plugin_orgchart#1]
This page Head is the root of the chart:

=== Head ===
---- dataentry orgchart hidden ----
name_pageid : Head
in_title    :

This page Org is its child and should show the chart:

=== Org ===
---- dataentry orgchart hidden ----
name_pageid : Org
in_title    : Head

---- datatable orgchart includelinks ----
cols    : name_pageid, in_title, title, photo_img60
headers : Name, In, Role, Pic
sort    : name

However it shows this:
![org_chart_bug](https://cloud.githubusercontent.com/assets/5161535/6885326/f91bca5e-d623-11e4-969f-5be9e94e370c.png)

Then if we add another page:

=== Test ===
---- dataentry orgchart hidden ----
name_pageid : Test
in_title    : Org

so it's a child of Org which is a child of Head,
then we get this on Org page:
![org_chart_bug2](https://cloud.githubusercontent.com/assets/5161535/6885330/2296508e-d624-11e4-9bb8-f76060278a05.png)

and this if we show a chart on Head page:
![org_chart_bug3](https://cloud.githubusercontent.com/assets/5161535/6885323/c3200e06-d623-11e4-8f9b-306e28f774f2.png)

So all the charts are wrong.

See demo
http://earth.zen-do.ru/wiki/head
http://earth.zen-do.ru/wiki/org
http://earth.zen-do.ru/wiki/test

**Comment by chang-zhao** [comment]
When orgchart plugin is disabled, I see wrong links in dataentry tables, so it's probably a bug of Data Plugin.

**Comment by selfthinker** [comment]
Couid be this bug: https://github.com/splitbrain/dokuwiki-plugin-data/issues/150
and therefore be fixed by changing `in_title` to `in_page`.

**Comment by chang-zhao** [comment]
Yes, it is. Changing _title to _page works.

**Comment by chang-zhao** [comment]
By the way, simple string type gives the same bug as _title.
